# MUHAMMED AZEEM YOONUS
# AM.EN.U4CSE20344

In [2]:
from pandas import read_csv
path='meteorite-landings.csv'
data=read_csv(path)

In [10]:
print (data.shape)

(45716, 10)


In [8]:
# Create  a  one-dimensional  array  containing  numbers  between  5  and  20  using  the 'arrange()' function in the NumPy module.
import numpy as np

arr = np.arange(5, 21)
print(arr)


[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
# Create  an  array  of  numbers  from1  to  24  such  that  the  difference  between  two consecutive  numbers  is  4.  Create  an  array  of  numbers  from  1  to  24  such  that  the difference between two consecutive numbers is 4 and each item is a float.


def main():
    # Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4.
    arr1 = np.arange(1, 25, 4)
    print(arr1)
    # Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4 and each item is a float.
    arr2 = np.arange(1, 25, 4, dtype=float)
    print(arr2)

if __name__ == "__main__":
    main()

[ 1  5  9 13 17 21]
[ 1.  5.  9. 13. 17. 21.]


In [7]:
# Create an array containing 4 numbers between 1 to 25.

arr = np.random.randint(1, 25, 4)
print(arr)

[11  2 14  7]


In [22]:
# Create  an  array  containing  10  numbers  between  1  and  25  such  that  the  difference between two consecutive numbers is constant.
def main():
    arr = np.arange(1, 26, 2)
    print(arr[:10])

if __name__ == "__main__":
    main()

[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
# Create a three-dimensional NumPy array containing 40 random integers between 50 and 100
def main():
    # Create a three-dimensional NumPy array containing 40 random integers between 50 and 100
    arr = np.random.randint(50, 100, size=(2, 4, 5))
    print(arr)

if __name__ == "__main__":
    main()

[[[94 96 69 74 50]
  [65 76 58 80 56]
  [83 62 52 76 88]
  [55 54 58 65 65]]

 [[50 60 63 98 92]
  [65 50 59 86 76]
  [80 52 66 97 92]
  [83 54 54 87 60]]]


In [10]:
# Create a list of natural numbers from 1 to 15using the list comprehension method. Then convert the list into a NumPy array using the array() function.
def main():
    # Create a list of natural numbers from 1 to 15 using the list comprehension method.
    # Then convert the list into a NumPy array using the array() function.
    arr = np.array([i for i in range(1, 16)])
    print(arr)

if __name__ == "__main__":
    main()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [23]:
# Create a function to check whether the input lenghts represent the lengths of the side of a triangle.
def is_triangle(a, b, c):
    if a + b > c and a + c > b and b + c > a:
        return True
    else:
        return False

def main():
    print(is_triangle(3, 4, 5))
    print(is_triangle(1, 1, 1))
    print(is_triangle(3, 4, 1))

if __name__ == "__main__":
    main()

True
True
False


In [19]:
# Create a function to calculate the area of a triangle using the Heron's formula.

def area_of_triangle_using_heron_formula(a, b, c):
    s = (a + b + c) / 2
    area = np.sqrt(s * (s - a) * (s - b) * (s - c))
    return area

def main():
    a = 3
    b = 4
    c = 5
    area = area_of_triangle_using_heron_formula(a, b, c)
    print("The area of the triangle with sides of length", a, b, c, "is", area)

if __name__ == "__main__":
    main()

The area of the triangle with sides of length 3 4 5 is 6.0


In [25]:
'''
Write a program to perform following two tasks:a.Print the square root of numbers in the list.  b.Compute the value of c in the equation c=(√a2+b2).
'''

def main():
    # Create a list of natural numbers from 1 to 15 using the list comprehension method.
    # Then convert the list into a NumPy array using the array() function.
    arr = np.array([i for i in range(1, 16)])
    #print(arr)
    # Print the square root of numbers in the list.
    print(np.sqrt(arr)[-1])
    # Compute the value of c in the equation c=(√a2+b2).
    print(np.sqrt(arr**2 + 2)[-1])

if __name__ == "__main__":
    main()

3.872983346207417
15.066519173319364


In [18]:
# Write a program to change the dimension of an array (say my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.

def main():
    # Create a list of natural numbers from 1 to 15 using the list comprehension method.
    # Then convert the list into a NumPy array using the array() function.
    arr = np.array([i for i in range(1, 10)])
    print(arr)
    # Change the dimension of an array (say my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.
    arr = arr.reshape(3, 3)
    print(arr)
    arr = arr.tolist()
    print(arr)

if __name__ == "__main__":
    main()

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
